/**
 * Todo Api
 * API built for Angular todo application
 *
 * OpenAPI spec version: 2018.09.19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelError {
    code?: any;
    /**
     * The cause of the error.
     */
    message: string;
}
